### ISSUE TITLE
OSError: [Errno -9998] Invalid number of channels

### ISSUE THREAD

**Issue by Ikaros-521** [Ikaros-521/audio_player#1]
2023-11-05 15:44:32,202 - D:\GitHub_pro\audio_player\pkg\audio_player\utils\audio_play_center.py[line:86] - ERROR: Traceback (most recent call last):
  File "D:\GitHub_pro\audio_player\pkg\audio_player\utils\audio_play_center.py", line 65, in play_audio
    self.stream = self.audio.open(format=self.audio.get_format_from_width(wf.getsampwidth()),
  File "D:\GitHub_pro\audio_player\pkg\audio_player\Miniconda3\lib\site-packages\pyaudio\__init__.py", line 639, in open
    stream = PyAudio.Stream(self, *args, **kwargs)
  File "D:\GitHub_pro\audio_player\pkg\audio_player\Miniconda3\lib\site-packages\pyaudio\__init__.py", line 441, in __init__
    self._stream = pa.open(**arguments)
OSError: [Errno -9998] Invalid number of channels

**Comment by Ikaros-521** [comment]
换个声卡试试
