### ISSUE TITLE
出现如下错误后，不能继续播放音频

### ISSUE THREAD

**Issue by Ikaros-521** [Ikaros-521/audio_player#2]
```
2023-11-06 16:01:45,743 - D:\GitHub_pro\audio_player\utils\audio_play_center.py[line:117] - INFO: 添加音频数据={'voice_path': 'song/ikaros/枝垂樱.mp3', 'content': 'song/ikaros/枝垂樱.mp3'}
2023-11-06 16:01:45,743 - D:\GitHub_pro\audio_player\app.py[line:162] - INFO: 添加音频信息成功！
2023-11-06 16:01:45,746 - D:\GitHub_pro\audio_player\utils\audio_play_center.py[line:86] - ERROR: Traceback (most recent call last):
  File "src\\gevent\\_semaphore.py", line 249, in gevent._gevent_c_semaphore.Semaphore.acquire
  File "src\\gevent\\_abstract_linkable.py", line 521, in gevent._gevent_c_abstract_linkable.AbstractLinkable._wait
  File "src\\gevent\\_abstract_linkable.py", line 487, in gevent._gevent_c_abstract_linkable.AbstractLinkable._wait_core
  File "src\\gevent\\_abstract_linkable.py", line 490, in gevent._gevent_c_abstract_linkable.AbstractLinkable._wait_core
  File "src\\gevent\\_abstract_linkable.py", line 442, in gevent._gevent_c_abstract_linkable.AbstractLinkable._AbstractLinkable__wait_to_be_notified
  File "src\\gevent\\_abstract_linkable.py", line 451, in gevent._gevent_c_abstract_linkable.AbstractLinkable._switch_to_hub
  File "src\\gevent\\_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src\\gevent\\_greenlet_primitives.py", line 65, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src\\gevent\\_gevent_c_greenlet_primitives.pxd", line 35, in gevent._gevent_c_greenlet_primitives._greenlet_switch
gevent.exceptions.LoopExit: This operation would block forever
	Hub: <Hub '' at 0x2032f8e0e00 backend=default ptr=<cdata 'struct uv_loop_s *' 0x000002032FAC0030> pending=0 ref=0 callbacks=0 thread_ident=0x11f4>
	Handles:
[HandleState(handle=<cdata 'struct uv_handle_s *' 0x000002032E635BB8>, type=b'check', watcher=<gevent.libuv.loop.loop at 0x2032fa93400 backend=default ptr=<cdata 'struct uv_loop_s *' 0x000002032FAC0030> pending=0 ref=0 callbacks=0>, ref=0, active=1, closing=0),
 HandleState(handle=<cdata 'struct uv_handle_s *' 0x000002032E677958>, type=b'timer', watcher=<gevent.libuv.loop.loop at 0x2032fa93400 backend=default ptr=<cdata 'struct uv_loop_s *' 0x000002032FAC0030> pending=0 ref=0 callbacks=0>, ref=0, active=1, closing=0),
 HandleState(handle=<cdata 'struct uv_handle_s *' 0x000002032E636D98>, type=b'prepare', watcher=<gevent.libuv.loop.loop at 0x2032fa93400 backend=default ptr=<cdata 'struct uv_loop_s *' 0x000002032FAC0030> pending=0 ref=0 callbacks=0>, ref=0, active=1, closing=0),
 HandleState(handle=<cdata 'struct uv_handle_s *' 0x000002032E636AD8>, type=b'check', watcher=<gevent.libuv.loop.loop at 0x2032fa93400 backend=default ptr=<cdata 'struct uv_loop_s *' 0x000002032FAC0030> pending=0 ref=0 callbacks=0>, ref=1, active=0, closing=0),
 HandleState(handle=<cdata 'struct uv_handle_s *' 0x000002032E744C88>, type=b'async', watcher=<async_ at 0x2032fa91cf0 callback=<function AbstractLoop._init_loop_and_aux_watchers.<locals>.<lambda> at 0x000002032F9E6950> args=() watcher=<cdata 'struct uv_async_s *' owning 224 bytes> handle=<cdata 'void *' 0x000002032FAC7EC0> ref=False>, ref=0, active=1, closing=0)]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\GitHub_pro\audio_player\utils\audio_play_center.py", line 46, in play_audio
    data_json = self.audio_json_queue.get(block=True)
  File "D:\Miniconda\envs\ai_vtb\lib\queue.py", line 171, in get
    self.not_empty.wait()
  File "D:\Miniconda\envs\ai_vtb\lib\threading.py", line 320, in wait
    waiter.acquire()
  File "D:\Miniconda\envs\ai_vtb\lib\site-packages\gevent\thread.py", line 112, in acquire
    acquired = BoundedSemaphore.acquire(self, blocking, timeout)
  File "src\\gevent\\_semaphore.py", line 180, in gevent._gevent_c_semaphore.Semaphore.acquire
  File "src\\gevent\\_semaphore.py", line 260, in gevent._gevent_c_semaphore.Semaphore.acquire
  File "src\\gevent\\_semaphore.py", line 348, in gevent._gevent_c_semaphore.Semaphore._Semaphore__acquire_from_other_thread
  File "src\\gevent\\_semaphore.py", line 390, in gevent._gevent_c_semaphore.Semaphore._Semaphore__acquire_using_two_hubs
  File "src\\gevent\\_abstract_linkable.py", line 427, in gevent._gevent_c_abstract_linkable.AbstractLinkable._quiet_unlink_all
  File "src\\gevent\\_abstract_linkable.py", line 150, in gevent._gevent_c_abstract_linkable.AbstractLinkable.unlink
  File "src\\gevent\\_abstract_linkable.py", line 150, in gevent._gevent_c_abstract_linkable.AbstractLinkable.unlink
  File "src\\gevent\\_abstract_linkable.py", line 157, in gevent._gevent_c_abstract_linkable.AbstractLinkable.unlink
AttributeError: 'int' object has no attribute 'pending'

2023-11-06 16:01:45,749 - D:\GitHub_pro\audio_player\utils\audio_play_center.py[line:86] - ERROR: Traceback (most recent call last):
  File "D:\GitHub_pro\audio_player\utils\audio_play_center.py", line 48, in play_audio
    audio = AudioSegment.from_file(voice_path)
  File "D:\Miniconda\envs\ai_vtb\lib\site-packages\pydub\audio_segment.py", line 651, in from_file
    file, close_file = _fd_or_path_or_tempfile(file, 'rb', tempfile=False)
  File "D:\Miniconda\envs\ai_vtb\lib\site-packages\pydub\utils.py", line 60, in _fd_or_path_or_tempfile
    fd = open(fd, mode=mode)
FileNotFoundError: [Errno 2] No such file or directory: 'song/ikaros/枝垂樱.mp3'
```

**Comment by Ikaros-521** [comment]
```
2023-11-07 15:12:23,805 - D:\GitHub_pro\audio_player\utils\audio_play_center.py[line:86] - ERROR: Traceback (most recent call last):
  File "src\\gevent\\_semaphore.py", line 249, in gevent._gevent_c_semaphore.Semaphore.acquire
  File "src\\gevent\\_abstract_linkable.py", line 521, in gevent._gevent_c_abstract_linkable.AbstractLinkable._wait
  File "src\\gevent\\_abstract_linkable.py", line 487, in gevent._gevent_c_abstract_linkable.AbstractLinkable._wait_core
  File "src\\gevent\\_abstract_linkable.py", line 490, in gevent._gevent_c_abstract_linkable.AbstractLinkable._wait_core
  File "src\\gevent\\_abstract_linkable.py", line 442, in gevent._gevent_c_abstract_linkable.AbstractLinkable._AbstractLinkable__wait_to_be_notified
  File "src\\gevent\\_abstract_linkable.py", line 451, in gevent._gevent_c_abstract_linkable.AbstractLinkable._switch_to_hub
  File "src\\gevent\\_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src\\gevent\\_greenlet_primitives.py", line 65, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src\\gevent\\_gevent_c_greenlet_primitives.pxd", line 35, in gevent._gevent_c_greenlet_primitives._greenlet_switch
gevent.exceptions.LoopExit: This operation would block forever
	Hub: <Hub '' at 0x1fbf658e3e0 backend=default ptr=<cdata 'struct uv_loop_s *' 0x000001FBF68C8210> pending=0 ref=0 callbacks=0 thread_ident=0x36cc>
	Handles:
[HandleState(handle=<cdata 'struct uv_handle_s *' 0x000001FBF523DEB8>, type=b'check', watcher=<gevent.libuv.loop.loop at 0x1fbf66ff0d0 backend=default ptr=<cdata 'struct uv_loop_s *' 0x000001FBF68C8210> pending=0 ref=0 callbacks=0>, ref=0, active=1, closing=0),
 HandleState(handle=<cdata 'struct uv_handle_s *' 0x000001FBF5333248>, type=b'timer', watcher=<gevent.libuv.loop.loop at 0x1fbf66ff0d0 backend=default ptr=<cdata 'struct uv_loop_s *' 0x000001FBF68C8210> pending=0 ref=0 callbacks=0>, ref=0, active=1, closing=0),
 HandleState(handle=<cdata 'struct uv_handle_s *' 0x000001FBF523E9B8>, type=b'prepare', watcher=<gevent.libuv.loop.loop at 0x1fbf66ff0d0 backend=default ptr=<cdata 'struct uv_loop_s *' 0x000001FBF68C8210> pending=0 ref=0 callbacks=0>, ref=0, active=1, closing=0),
 HandleState(handle=<cdata 'struct uv_handle_s *' 0x000001FBF523EF38>, type=b'check', watcher=<gevent.libuv.loop.loop at 0x1fbf66ff0d0 backend=default ptr=<cdata 'struct uv_loop_s *' 0x000001FBF68C8210> pending=0 ref=0 callbacks=0>, ref=1, active=0, closing=0),
 HandleState(handle=<cdata 'struct uv_handle_s *' 0x000001FBF53E54C8>, type=b'async', watcher=<async_ at 0x1fbf66ff430 callback=<function AbstractLoop._init_loop_and_aux_watchers.<locals>.<lambda> at 0x000001FBF665A3B0> args=() watcher=<cdata 'struct uv_async_s *' owning 224 bytes> handle=<cdata 'void *' 0x000001FBF685DC80> ref=False>, ref=0, active=1, closing=0)]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\GitHub_pro\audio_player\utils\audio_play_center.py", line 46, in play_audio
    data_json = self.audio_json_queue.get(block=True)
  File "D:\Miniconda\envs\ai_vtb\lib\queue.py", line 171, in get
    self.not_empty.wait()
  File "D:\Miniconda\envs\ai_vtb\lib\threading.py", line 320, in wait
    waiter.acquire()
  File "D:\Miniconda\envs\ai_vtb\lib\site-packages\gevent\thread.py", line 112, in acquire
    acquired = BoundedSemaphore.acquire(self, blocking, timeout)
  File "src\\gevent\\_semaphore.py", line 180, in gevent._gevent_c_semaphore.Semaphore.acquire
  File "src\\gevent\\_semaphore.py", line 260, in gevent._gevent_c_semaphore.Semaphore.acquire
  File "src\\gevent\\_semaphore.py", line 348, in gevent._gevent_c_semaphore.Semaphore._Semaphore__acquire_from_other_thread
  File "src\\gevent\\_semaphore.py", line 390, in gevent._gevent_c_semaphore.Semaphore._Semaphore__acquire_using_two_hubs
  File "src\\gevent\\_abstract_linkable.py", line 427, in gevent._gevent_c_abstract_linkable.AbstractLinkable._quiet_unlink_all
  File "src\\gevent\\_abstract_linkable.py", line 150, in gevent._gevent_c_abstract_linkable.AbstractLinkable.unlink
  File "src\\gevent\\_abstract_linkable.py", line 150, in gevent._gevent_c_abstract_linkable.AbstractLinkable.unlink
  File "src\\gevent\\_abstract_linkable.py", line 157, in gevent._gevent_c_abstract_linkable.AbstractLinkable.unlink
AttributeError: 'int' object has no attribute 'pending'

```

**Comment by Ikaros-521** [comment]
没有测试出来了，先关了
